### ISSUE TITLE
Missing License 

### ISSUE THREAD

**Issue by aeksco** [Printrbot/firmware-updater#1]
This repository should have a license attached to it. I've would like to fork this codebase for another project but without a proper license I'm not _technically_ in a legal position to do so:

[Github - Open-Source Licensing](https://help.github.com/articles/open-source-licensing/)

> You're under no obligation to choose a license. It's your right not to include one with your code or project, but please be aware of the implications. Generally speaking, the absence of a license means that the default copyright laws apply. This means that you retain all rights to your source code and that nobody else may reproduce, distribute, or create derivative works from your work. This might not be what you intend.

At your convenience please add a license to this repository - thanks!

**Comment by mickbalaban** [comment]
Hi aeksco, thanks for pointing that out. License is now added to the repo.
